# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e04e0acdc3b2e962e0c6814ddbaae5c962e03fdfe5cee620b570d98116c73a00070204511d46c2ee8c6df98853e03eec00d8ed8f2076d6c23cba74bfa5085eb

test:
  secret_key_base: ab449081ea2a5aaf1f5f66103c4f2d4862fbcdae005d8656bf14a0304a0f46ce00bee18b6531bf1bc3a6ace1f17bac724c237260b8420bed41277435ecb48352

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
